#%RAML 1.0 NamedExample
example:

  CustomerName: Michael Young
  CustomerEmail: Michael.Young@gmail.com
  CustomerAddress:
    Street1: 155 Tariff Street
    Street2: Apt B
    City: Sayville
    StateOrProvince: NY
    PostalCode: 11782
    Country: USA