#%RAML 1.0 NamedExample
example:
	
  OrderID?: 2
  CustomerID: 2
  ProductID: 3
  OrderDateTime: 2022-05-18 17:37:49
  ProductName: MENS BACKPACK
  ProductDescription: Great backpack for men
  ProductPrice: 45.00
  Count: 2250
  ProductSize: NA
  CustomerName: Michael Young
  CustomerEmail: michael.young@gmail.com
  CustomerAddress:
    Street1: 155 Tariff Avenue
    Street2?: Apt B
    City: Sayville
    StateOrProvince: NY
    PostalCode: 11805
    Country: USA